### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by He-Yichen** [sherry6247/SHAPE#4]
Hi, when I create the conda environment through yaml file, The runtime error is:
Solving environment: failed

ResolvePackageNotFound:
  - torchvision==0.2.2=py_3
 
My platform is also Linux. My operating system is Ubuntu 22.04.3, could you help look into the problem?

**Comment by qzsmile** [comment]
hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved?
When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows:
self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device)
TypeError: forward() got an unexpected keyword argument 'device'

**Comment by sherry6247** [comment]
> Hi, when I create the conda environment through yaml file, The runtime error is: Solving environment: failed
> 
> ResolvePackageNotFound:
> 
> * torchvision==0.2.2=py_3
> 
> My platform is also Linux. My operating system is Ubuntu 22.04.3, could you help look into the problem?

You can try pip install torchvision==0.2.2

**Comment by sherry6247** [comment]
> hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved? When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows: self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an unexpected keyword argument 'device'

Maybe the version of x-transformer you installed is wrong

**Comment by He-Yichen** [comment]
> > hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved? When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows: self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an unexpected keyword argument 'device'
> 
> Maybe the version of x-transformer you installed is wrong

@sherry6247 Hi, When I run main.py, I got Traceback (most recent call last):
  File "/home/heyichen/SHAPE/src/main.py", line 24, in <module>
    from shape_model import SHAPE
  File "/home/heyichen/SHAPE/src/shape_model.py", line 13, in <module>
    from block_recurrent_transformer.transformer import BlockRecurrentAttention
  File "/home/heyichen/SHAPE/src/block_recurrent_transformer/transformer.py", line 19, in <module>
    patch_typeguard()
  File "/home/heyichen/.conda/envs/SHAPE/lib/python3.8/site-packages/torchtyping/typechecker.py", line 271, in patch_typeguard
    class _CallMemo(typeguard._CallMemo):
  File "/home/heyichen/.conda/envs/SHAPE/lib/python3.8/site-packages/typeguard/__init__.py", line 43, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'typeguard' has no attribute '_CallMemo'

Could you tell me the version of x-transformer, torchtyping and typeguard you installed?

**Comment by qzsmile** [comment]
> > hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved? When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows: self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an unexpected keyword argument 'device'
> 
> Maybe the version of x-transformer you installed is wrong


> > hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved? When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows: self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an unexpected keyword argument 'device'
> 
> Maybe the version of x-transformer you installed is wrong

Can you tell me the specific version numbers of x-transformers, torchtyping, and typeguard that you are using? I would greatly appreciate it.

**Comment by qzsmile** [comment]
> > hello,I encountered the following issue during the runtime. What might be the cause, and how can it be resolved? When importing 'Beam' from 'recommend.py', an error occurs indicating the absence of a configuration file. After commenting it out and continuing the execution, a new error arises as follows: self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an unexpected keyword argument 'device'
> 
> Maybe the version of x-transformer you installed is wrong

Can you tell me the specific version numbers of x-transformers, torchtyping, and typeguard that you are using? I would greatly appreciate it.

**Comment by fxx765** [comment]
May I ask if your problem has been solved?

**Comment by fxx765** [comment]
> > > 你好，我在运行过程中遇到了以下问题。可能是什么原因造成的，如何解决？从'recommend.py'导入'Beam'时，出现错误，提示缺少配置文件。将其注释掉并继续执行后，出现新的错误，如下所示：self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device) TypeError: forward() got an expected keyword arc 'device'
> > 
> > 
> > 可能是你安装的x-transformer版本不对
> 
> @sherry6247嗨，当我运行 main.py 时，我得到了 Traceback（最近一次调用最后一次）： 文件“/home/heyichen/SHAPE/src/main.py”，第 24 行，来自 shape_model 导入 SHAPE 文件“/home/heyichen/SHAPE/src/shape_model.py”，第 13 行，来自 block_recurrent_transformer.transformer 导入 BlockRecurrentAttention 文件“/home/heyichen/SHAPE/src/block_recurrent_transformer/transformer.py”，第 19 行，在 patch_typeguard() 文件“/home/heyichen/.conda/envs/SHAPE/lib/python3.8/site-packages/torchtyping/typechecker.py”，第 271 行，在 patch_typeguard 类 _CallMemo（typeguard._CallMemo）： 文件“/home/heyichen/.conda/envs/SHAPE/lib/python3.8/site-packages/typeguard/ **init** .py”，第 43 行，在**getattr**中 引发 AttributeError(f"module { **name** !r} 没有属性 {name!r}") AttributeError: module 'typeguard' 没有属性 '_CallMemo'
> 
> 你能告诉我你安装的 x-transformer、torchtyping 和 typeguard 的版本吗？

请问你的问题解决了吗？我也遇到了同样的问题
